### ISSUE TITLE
It doesn't work for Jquery ^1.12.1

### ISSUE THREAD

**Issue by daveek** [AbdallaMohamed/Angular-Maphilight#1]
I've try to implement this directive in my PWA, with Angular 1.5.6 and Jquery 3.1.1, and it doesn't work.
It shows me this error message:
`TypeError: a.indexOf is not a function
    at r.fn.init.r.fn.load (jquery.min.js:4)
    at drawCanvas (angular.maphilight.js:506)
    at Scope.$digest (angular.js:17755)
    at Scope.$apply (angular.js:18021)
    at done (angular.js:12002)
    at completeRequest (angular.js:12211)
    at XMLHttpRequest.requestLoaded (angular.js:12139)`

**Comment by pradeepn** [comment]
`Line 250 Replace map.size() with map.length`
array.size() has been [deprecated ](https://api.jquery.com/size/)size jquery 1.8
Working fine with ng1.6.3 jquery 3.1.1

**Comment by AbdallaMohamed** [comment]
Pushed fixes. Thanks @pradeepn
